---
galaxy_info:
  author: KindStack Team
  description: AWS Application Load Balancer 관리 Role
  company: 
  license: MIT
  min_ansible_version: 2.9
  platforms:
    - name: EL
      versions:
        - all
    - name: Ubuntu
      versions:
        - all
  galaxy_tags:
    - aws
    - elb
    - loadbalancer

dependencies: []
