---
collections:
  # AWS 관리용
  - name: amazon.aws
    version: ">=8.0.0"
  
  # Kubernetes 관리용  
  - name: kubernetes.core
    version: ">=3.0.0"
    
  # 일반적인 유틸리티들
  - name: community.general
    version: ">=8.0.0"
    
  # POSIX 시스템 관리
  - name: ansible.posix
    version: ">=1.5.0"
