---
all:
  hosts:
    localhost:
      ansible_connection: local
      ansible_python_interpreter: "{{ ansible_playbook_python }}"
      
  vars:
    # AWS 설정
    aws_region: us-east-1
    aws_access_key: "{{ ansible_env.AWS_ACCESS_KEY_ID | default('test') }}"
    aws_secret_key: "{{ ansible_env.AWS_SECRET_ACCESS_KEY | default('test') }}"
    
    # 기본 애플리케이션 설정
    app_name: "{{ ansible_env.APP_NAME | default('sample-app') }}"
    app_image: "{{ ansible_env.DOCKER_IMAGE | default('nginx:alpine') }}"
    app_port: 80
    app_replicas: 2
    
    # 도메인 설정
    domain_name: "{{ ansible_env.DOMAIN | default('example.com') }}"
    subdomain: "{{ app_name }}"
    full_domain: "{{ subdomain }}.{{ domain_name }}"
    
    # Kubernetes 설정
    k8s_namespace: "{{ app_name }}"
    k8s_context: "{{ ansible_env.K8S_CONTEXT | default('kind-kind') }}"
    
    # 환경 설정
    env_config: "{{ ansible_env.ENV_CONFIG | default('') }}"
    deployment_id: "{{ ansible_env.DEPLOYMENT_ID | default('1') }}"
    
    # Bridge 서버 설정
    bridge_server_url: "{{ ansible_env.BRIDGE_SERVER_URL | default('http://localhost:8080') }}"
